# Generated by Django 5.0.1 on 2024-01-08 08:43

import files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
                ("icon", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name": "About",
                "verbose_name_plural": "About",
            },
        ),
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("is_seen", models.BooleanField(default=False)),
                ("register_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="introduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_img",
                    models.ImageField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                ("first_name", models.CharField(blank=True, max_length=50, null=True)),
                ("last_name", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                (
                    "cv",
                    models.FileField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                ("description", models.TextField()),
                ("update_date", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="socialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("linkedin", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("gitHub", models.CharField(max_length=100)),
                ("update_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
