# Generated by Django 5.0.1 on 2024-01-09 01:13

import files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_introduction_cv_alter_introduction_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="mobile_number",
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="introduction",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="main_img",
            field=models.ImageField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
    ]
