# Generated by Django 5.0.1 on 2024-01-11 21:44

import files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_contact_mobile_number_alter_introduction_cv_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="introduction",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="main_img",
            field=models.ImageField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
    ]
