# Generated by Django 5.0.1 on 2024-01-12 05:36

import files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0008_alter_introduction_cv_alter_introduction_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedia",
            name="telegram",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="cv",
            field=models.FileField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
        migrations.AlterField(
            model_name="introduction",
            name="main_img",
            field=models.ImageField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
    ]
