# Generated by Django 5.0.1 on 2024-01-08 08:43

import django.db.models.deletion
import django.utils.timezone
import files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("skill", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Objective",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Outcomes_achieved",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Role_project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("project_name", models.CharField(max_length=50)),
                (
                    "short_description",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("team_size", models.PositiveIntegerField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(default=django.utils.timezone.now)),
                ("update_date", models.DateTimeField(auto_now_add=True)),
                (
                    "main_img",
                    models.ImageField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                (
                    "main_video",
                    models.ImageField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "slug",
                    models.SlugField(max_length=30, unique=True, verbose_name="slug"),
                ),
                (
                    "objective",
                    models.ManyToManyField(blank=True, to="project.objective"),
                ),
                (
                    "outcomes_achieved",
                    models.ManyToManyField(blank=True, to="project.outcomes_achieved"),
                ),
                (
                    "skills_used",
                    models.ManyToManyField(
                        blank=True, related_name="skills_project", to="skill.skill"
                    ),
                ),
                (
                    "your_role_project",
                    models.ManyToManyField(blank=True, to="project.role_project"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Project_gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_img",
                    models.ImageField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        blank=True, help_text="Sort images for display", null=True
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="project_gallery",
                        to="project.project",
                    ),
                ),
            ],
        ),
    ]
