# Generated by Django 5.0.1 on 2024-01-08 08:43

import files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "main_img",
                    models.ImageField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        help_text="It should not be more than 130 characters"
                    ),
                ),
                ("update_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField(default=False)),
            ],
        ),
    ]
