# Generated by Django 5.0.1 on 2024-05-04 01:07

import files
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("service", "0010_alter_service_main_img"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="main_img",
            field=models.ImageField(
                blank=True, null=True, upload_to=files.FileUpload.upload_to
            ),
        ),
    ]
