# Generated by Django 5.0.1 on 2024-01-08 08:43

import django.db.models.deletion
import files
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="skillGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("is_active", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("percent", models.PositiveIntegerField()),
                (
                    "icon",
                    models.FileField(
                        blank=True, null=True, upload_to=files.FileUpload.upload_to
                    ),
                ),
                ("update_date", models.DateTimeField(auto_now=True, null=True)),
                ("is_active", models.BooleanField()),
                (
                    "skill_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills_of_group",
                        to="skill.skillgroup",
                    ),
                ),
            ],
        ),
    ]
